### ISSUE TITLE
[Glitch/Issue] Can't run any other commands when making a typo

### ISSUE THREAD

**Issue by shaunikm** [gadhagod/TerminalToDo#2]
OS System: mac OS Catalina 10.15.6

Hi, when trying to view my tasks, I accidentally made a type in the <code>view</code> command, misspelling it as <code>view'</code>.

<img width="358" alt="Screenshot1" src="https://user-images.githubusercontent.com/68877932/94493518-b00df800-01a1-11eb-987c-e892308f75df.png">

As you can see, I misspelled <code>view</code> and it put me in this mode where I can't run any command or do anything to quit out of it. Although this can be my fault, I think there should be a way to quit out of this mode. (Sorry if there is a way to quit out of it. I don't know it yet.) I know it is possible to just close the command line and restart it, but this can be annoying.

**Comment by gadhagod** [comment]
Thanks for reporting this issue. You can type <code>exit</code> to exit that mode. With ('), you can run multiple commands, so it was waiting for you to type another command. This is not an issue from the code.

**Comment by shaunikm** [comment]
I tried typing exit, but it didn't work. Are you sure this works?

<img width="326" alt="Screen Shot 2020-09-28 at 4 32 16 PM" src="https://user-images.githubusercontent.com/68877932/94496083-46451c80-01a8-11eb-8ef5-99c70a4bb4d7.png">

**Comment by gadhagod** [comment]
Try typing (') and <kbd>Enter</kbd>.

**Comment by shaunikm** [comment]
Ok, that works. Thanks!
